// NCAA Power Conference Schools - 2025-2026 realignment

var NCAA_SCHOOLS = [
	// SEC (16 schools)
	{
		name: "University of Alabama",
		shortName: "Alabama",
		mascot: "Crimson Tide",
		conference: "SEC",
		city: "Tuscaloosa",
		state: "AL",
		lat: 33.2098,
		lon: -87.5692,
		colorPrimary: "#9E1B32",
		colorSecondary: "#828A8F",
		hintRegion: "Southeast",
	},
	{
		name: "University of Arkansas",
		shortName: "Arkansas",
		mascot: "Razorbacks",
		conference: "SEC",
		city: "Fayetteville",
		state: "AR",
		lat: 36.0726,
		lon: -94.1732,
		colorPrimary: "#C4243E",
		colorSecondary: "#F1E4DE",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "Auburn University",
		shortName: "Auburn",
		mascot: "Tigers",
		conference: "SEC",
		city: "Auburn",
		state: "AL",
		lat: 32.6024,
		lon: -85.4870,
		colorPrimary: "#FF6600",
		colorSecondary: "#003366",
		hintRegion: "Southeast",
	},
	{
		name: "University of Florida",
		shortName: "Florida",
		mascot: "Gators",
		conference: "SEC",
		city: "Gainesville",
		state: "FL",
		lat: 29.6436,
		lon: -82.3549,
		colorPrimary: "#0033CC",
		colorSecondary: "#FF6600",
		hintRegion: "Southeast",
	},
	{
		name: "University of Georgia",
		shortName: "Georgia",
		mascot: "Bulldogs",
		conference: "SEC",
		city: "Athens",
		state: "GA",
		lat: 33.9519,
		lon: -83.3576,
		colorPrimary: "#BA0021",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "University of Kentucky",
		shortName: "Kentucky",
		mascot: "Wildcats",
		conference: "SEC",
		city: "Lexington",
		state: "KY",
		lat: 38.0304,
		lon: -84.4699,
		colorPrimary: "#003366",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "Louisiana State University",
		shortName: "LSU",
		mascot: "Tigers",
		conference: "SEC",
		city: "Baton Rouge",
		state: "LA",
		lat: 30.4130,
		lon: -91.1871,
		colorPrimary: "#461D7C",
		colorSecondary: "#FDD835",
		hintRegion: "Southeast",
	},
	{
		name: "University of Mississippi",
		shortName: "Ole Miss",
		mascot: "Rebels",
		conference: "SEC",
		city: "Oxford",
		state: "MS",
		lat: 34.3642,
		lon: -89.5344,
		colorPrimary: "#DC143C",
		colorSecondary: "#003478",
		hintRegion: "Southeast",
	},
	{
		name: "Mississippi State University",
		shortName: "Mississippi State",
		mascot: "Bulldogs",
		conference: "SEC",
		city: "Starkville",
		state: "MS",
		lat: 33.4549,
		lon: -88.7903,
		colorPrimary: "#660033",
		colorSecondary: "#FFCC00",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "University of Missouri",
		shortName: "Missouri",
		mascot: "Tigers",
		conference: "SEC",
		city: "Columbia",
		state: "MO",
		lat: 38.2919,
		lon: -92.3388,
		colorPrimary: "#000000",
		colorSecondary: "#FFD700",
		hintRegion: "Midwest",
	},
	{
		name: "University of Oklahoma",
		shortName: "Oklahoma",
		mascot: "Sooners",
		conference: "SEC",
		city: "Norman",
		state: "OK",
		lat: 35.2087,
		lon: -97.4405,
		colorPrimary: "#CC0000",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southwest",
	},
	{
		name: "University of South Carolina",
		shortName: "South Carolina",
		mascot: "Gamecocks",
		conference: "SEC",
		city: "Columbia",
		state: "SC",
		lat: 34.1193,
		lon: -81.0263,
		colorPrimary: "#73000A",
		colorSecondary: "#000000",
		hintRegion: "Southeast",
	},
	{
		name: "University of Tennessee",
		shortName: "Tennessee",
		mascot: "Volunteers",
		conference: "SEC",
		city: "Knoxville",
		state: "TN",
		lat: 35.9558,
		lon: -83.9265,
		colorPrimary: "#FF8200",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southeast",
	},
	{
		name: "Texas A&M University",
		shortName: "Texas A&M",
		mascot: "Aggies",
		conference: "SEC",
		city: "College Station",
		state: "TX",
		lat: 30.6167,
		lon: -96.3422,
		colorPrimary: "#500000",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southwest",
	},
	{
		name: "University of Texas",
		shortName: "Texas",
		mascot: "Longhorns",
		conference: "SEC",
		city: "Austin",
		state: "TX",
		lat: 30.2833,
		lon: -97.7339,
		colorPrimary: "#CC5500",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southwest",
	},
	{
		name: "Vanderbilt University",
		shortName: "Vanderbilt",
		mascot: "Commodores",
		conference: "SEC",
		city: "Nashville",
		state: "TN",
		lat: 36.1446,
		lon: -86.8016,
		colorPrimary: "#000000",
		colorSecondary: "#FFD700",
		colorSwap: true,
		hintRegion: "Southeast",
	},

	// Big Ten (18 schools)
	{
		name: "University of Illinois",
		shortName: "Illinois",
		mascot: "Fighting Illini",
		conference: "Big Ten",
		city: "Urbana",
		state: "IL",
		lat: 40.1164,
		lon: -88.2434,
		colorPrimary: "#003D7A",
		colorSecondary: "#FF6600",
		hintRegion: "Midwest",
	},
	{
		name: "Indiana University",
		shortName: "Indiana",
		mascot: "Hoosiers",
		conference: "Big Ten",
		city: "Bloomington",
		state: "IN",
		lat: 39.1684,
		lon: -86.5244,
		colorPrimary: "#990000",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Iowa",
		shortName: "Iowa",
		mascot: "Hawkeyes",
		conference: "Big Ten",
		city: "Iowa City",
		state: "IA",
		lat: 41.9603,
		lon: -91.6350,
		colorPrimary: "#000000",
		colorSecondary: "#FFD700",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Maryland",
		shortName: "Maryland",
		mascot: "Terrapins",
		conference: "Big Ten",
		city: "College Park",
		state: "MD",
		lat: 38.9869,
		lon: -76.9426,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "University of Michigan",
		shortName: "Michigan",
		mascot: "Wolverines",
		conference: "Big Ten",
		city: "Ann Arbor",
		state: "MI",
		lat: 42.2656,
		lon: -83.7430,
		colorPrimary: "#00274C",
		colorSecondary: "#FFCC00",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Michigan State University",
		shortName: "Michigan State",
		mascot: "Spartans",
		conference: "Big Ten",
		city: "East Lansing",
		state: "MI",
		lat: 42.7335,
		lon: -84.4867,
		colorPrimary: "#18453B",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Minnesota",
		shortName: "Minnesota",
		mascot: "Golden Gophers",
		conference: "Big Ten",
		city: "Minneapolis",
		state: "MN",
		lat: 44.9747,
		lon: -93.2277,
		colorPrimary: "#8B0000",
		colorSecondary: "#FFD700",
		hintRegion: "Midwest",
	},
	{
		name: "University of Nebraska",
		shortName: "Nebraska",
		mascot: "Cornhuskers",
		conference: "Big Ten",
		city: "Lincoln",
		state: "NE",
		lat: 40.8258,
		lon: -96.7017,
		colorPrimary: "#CC0000",
		colorSecondary: "#FFFFFF",
		hintRegion: "Midwest",
	},
	{
		name: "Northwestern University",
		shortName: "Northwestern",
		mascot: "Wildcats",
		conference: "Big Ten",
		city: "Evanston",
		state: "IL",
		lat: 42.0534,
		lon: -87.6738,
		colorPrimary: "#4D2DB7",
		colorSecondary: "#FFFFFF",
		hintRegion: "Midwest",
	},
	{
		name: "Ohio State University",
		shortName: "Ohio State",
		mascot: "Buckeyes",
		conference: "Big Ten",
		city: "Columbus",
		state: "OH",
		lat: 40.0084,
		lon: -83.1074,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Oregon",
		shortName: "Oregon",
		mascot: "Ducks",
		conference: "Big Ten",
		city: "Eugene",
		state: "OR",
		lat: 44.0521,
		lon: -123.0868,
		colorPrimary: "#007030",
		colorSecondary: "#FEE11A",
		hintRegion: "Pacific",
	},
	{
		name: "Pennsylvania State University",
		shortName: "Penn State",
		mascot: "Nittany Lions",
		conference: "Big Ten",
		city: "University Park",
		state: "PA",
		lat: 40.8135,
		lon: -77.8601,
		colorPrimary: "#001A66",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "Purdue University",
		shortName: "Purdue",
		mascot: "Boilermakers",
		conference: "Big Ten",
		city: "West Lafayette",
		state: "IN",
		lat: 40.4258,
		lon: -87.0081,
		colorPrimary: "#000000",
		colorSecondary: "#FFD700",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Rutgers University",
		shortName: "Rutgers",
		mascot: "Scarlet Knights",
		conference: "Big Ten",
		city: "New Brunswick",
		state: "NJ",
		lat: 40.5243,
		lon: -74.4732,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "University of Southern California",
		shortName: "USC",
		mascot: "Trojans",
		conference: "Big Ten",
		city: "Los Angeles",
		state: "CA",
		lat: 34.0195,
		lon: -118.2882,
		colorPrimary: "#990000",
		colorSecondary: "#FFD700",
		hintRegion: "Pacific",
	},
	{
		name: "University of California, Los Angeles",
		shortName: "UCLA",
		mascot: "Bruins",
		conference: "Big Ten",
		city: "Los Angeles",
		state: "CA",
		lat: 34.0709,
		lon: -118.4468,
		colorPrimary: "#003DA5",
		colorSecondary: "#FFD700",
		hintRegion: "Pacific",
	},
	{
		name: "University of Washington",
		shortName: "Washington",
		mascot: "Huskies",
		conference: "Big Ten",
		city: "Seattle",
		state: "WA",
		lat: 47.6550,
		lon: -122.3035,
		colorPrimary: "#4B2C6F",
		colorSecondary: "#FFD700",
		hintRegion: "Pacific",
	},
	{
		name: "University of Wisconsin",
		shortName: "Wisconsin",
		mascot: "Badgers",
		conference: "Big Ten",
		city: "Madison",
		state: "WI",
		lat: 43.0731,
		lon: -89.4012,
		colorPrimary: "#C60C30",
		colorSecondary: "#FFFFFF",
		hintRegion: "Midwest",
	},

	// Big 12 (16 schools)
	{
		name: "University of Arizona",
		shortName: "Arizona",
		mascot: "Wildcats",
		conference: "Big 12",
		city: "Tucson",
		state: "AZ",
		lat: 32.2319,
		lon: -110.9501,
		colorPrimary: "#0013A3",
		colorSecondary: "#CC0000",
		hintRegion: "Southwest",
	},
	{
		name: "Arizona State University",
		shortName: "Arizona State",
		mascot: "Sun Devils",
		conference: "Big 12",
		city: "Tempe",
		state: "AZ",
		lat: 33.4255,
		lon: -111.9286,
		colorPrimary: "#8B2252",
		colorSecondary: "#FFC52F",
		hintRegion: "Southwest",
	},
	{
		name: "Baylor University",
		shortName: "Baylor",
		mascot: "Bears",
		conference: "Big 12",
		city: "Waco",
		state: "TX",
		lat: 31.5486,
		lon: -97.1164,
		colorPrimary: "#003D7A",
		colorSecondary: "#FFD700",
		hintRegion: "Southwest",
	},
	{
		name: "Brigham Young University",
		shortName: "BYU",
		mascot: "Cougars",
		conference: "Big 12",
		city: "Provo",
		state: "UT",
		lat: 40.2338,
		lon: -111.6585,
		colorPrimary: "#003366",
		colorSecondary: "#FFFFFF",
		hintRegion: "Mountain",
	},
	{
		name: "University of Central Florida",
		shortName: "UCF",
		mascot: "Knights",
		conference: "Big 12",
		city: "Orlando",
		state: "FL",
		lat: 28.6024,
		lon: -81.2005,
		colorPrimary: "#000000",
		colorSecondary: "#FFD700",
		hintRegion: "Southeast",
	},
	{
		name: "University of Cincinnati",
		shortName: "Cincinnati",
		mascot: "Bearcats",
		conference: "Big 12",
		city: "Cincinnati",
		state: "OH",
		lat: 39.1331,
		lon: -84.5186,
		colorPrimary: "#000000",
		colorSecondary: "#EF3B39",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Colorado",
		shortName: "Colorado",
		mascot: "Buffaloes",
		conference: "Big 12",
		city: "Boulder",
		state: "CO",
		lat: 40.0064,
		lon: -105.2605,
		colorPrimary: "#000000",
		colorSecondary: "#FFCC00",
		hintRegion: "Mountain",
	},
	{
		name: "University of Houston",
		shortName: "Houston",
		mascot: "Cougars",
		conference: "Big 12",
		city: "Houston",
		state: "TX",
		lat: 29.7589,
		lon: -95.3677,
		colorPrimary: "#CC0000",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Southwest",
	},
	{
		name: "Iowa State University",
		shortName: "Iowa State",
		mascot: "Cyclones",
		conference: "Big 12",
		city: "Ames",
		state: "IA",
		lat: 42.0115,
		lon: -93.6318,
		colorPrimary: "#990000",
		colorSecondary: "#FFD700",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Kansas",
		shortName: "Kansas",
		mascot: "Jayhawks",
		conference: "Big 12",
		city: "Lawrence",
		state: "KS",
		lat: 38.9596,
		lon: -95.2672,
		colorPrimary: "#0051BA",
		colorSecondary: "#EF4601",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Kansas State University",
		shortName: "Kansas State",
		mascot: "Wildcats",
		conference: "Big 12",
		city: "Manhattan",
		state: "KS",
		lat: 39.2184,
		lon: -97.5952,
		colorPrimary: "#512B82",
		colorSecondary: "#FFFFFF",
		hintRegion: "Midwest",
	},
	{
		name: "Oklahoma State University",
		shortName: "Oklahoma State",
		mascot: "Cowboys",
		conference: "Big 12",
		city: "Stillwater",
		state: "OK",
		lat: 36.1186,
		lon: -97.0734,
		colorPrimary: "#FF6A1D",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Southwest",
	},
	{
		name: "Texas Christian University",
		shortName: "TCU",
		mascot: "Horned Frogs",
		conference: "Big 12",
		city: "Fort Worth",
		state: "TX",
		lat: 32.7555,
		lon: -97.3308,
		colorPrimary: "#4D1979",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southwest",
	},
	{
		name: "Texas Tech University",
		shortName: "Texas Tech",
		mascot: "Red Raiders",
		conference: "Big 12",
		city: "Lubbock",
		state: "TX",
		lat: 33.5850,
		lon: -101.8746,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		hintRegion: "Southwest",
	},
	{
		name: "University of Utah",
		shortName: "Utah",
		mascot: "Utes",
		conference: "Big 12",
		city: "Salt Lake City",
		state: "UT",
		lat: 40.7629,
		lon: -111.8410,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		hintRegion: "Mountain",
	},
	{
		name: "West Virginia University",
		shortName: "West Virginia",
		mascot: "Mountaineers",
		conference: "Big 12",
		city: "Morgantown",
		state: "WV",
		lat: 39.6334,
		lon: -79.9559,
		colorPrimary: "#003366",
		colorSecondary: "#FFD700",
		colorSwap: true,
		hintRegion: "Southeast",
	},

	// ACC (18 schools)
	{
		name: "Boston College",
		shortName: "Boston College",
		mascot: "Eagles",
		conference: "ACC",
		city: "Chestnut Hill",
		state: "MA",
		lat: 42.3356,
		lon: -71.1677,
		colorPrimary: "#8B0000",
		colorSecondary: "#FFD700",
		hintRegion: "Northeast",
	},
	{
		name: "University of California, Berkeley",
		shortName: "Cal",
		mascot: "Golden Bears",
		conference: "ACC",
		city: "Berkeley",
		state: "CA",
		lat: 37.8722,
		lon: -122.2597,
		colorPrimary: "#003831",
		colorSecondary: "#FFD700",
		colorSwap: true,
		hintRegion: "Pacific",
	},
	{
		name: "Clemson University",
		shortName: "Clemson",
		mascot: "Tigers",
		conference: "ACC",
		city: "Clemson",
		state: "SC",
		lat: 34.6836,
		lon: -82.8374,
		colorPrimary: "#F66733",
		colorSecondary: "#522D80",
		hintRegion: "Southeast",
	},
	{
		name: "Duke University",
		shortName: "Duke",
		mascot: "Blue Devils",
		conference: "ACC",
		city: "Durham",
		state: "NC",
		lat: 36.0014,
		lon: -78.9382,
		colorPrimary: "#003366",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southeast",
	},
	{
		name: "Florida State University",
		shortName: "Florida State",
		mascot: "Seminoles",
		conference: "ACC",
		city: "Tallahassee",
		state: "FL",
		lat: 30.4383,
		lon: -84.2807,
		colorPrimary: "#8B0000",
		colorSecondary: "#FFD700",
		hintRegion: "Southeast",
	},
	{
		name: "Georgia Institute of Technology",
		shortName: "Georgia Tech",
		mascot: "Yellow Jackets",
		conference: "ACC",
		city: "Atlanta",
		state: "GA",
		lat: 33.7756,
		lon: -84.3963,
		colorPrimary: "#FFD700",
		colorSecondary: "#000000",
		hintRegion: "Southeast",
	},
	{
		name: "University of Louisville",
		shortName: "Louisville",
		mascot: "Cardinals",
		conference: "ACC",
		city: "Louisville",
		state: "KY",
		lat: 38.2009,
		lon: -85.7585,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "University of Miami",
		shortName: "Miami",
		mascot: "Hurricanes",
		conference: "ACC",
		city: "Coral Gables",
		state: "FL",
		lat: 25.7247,
		lon: -80.2798,
		colorPrimary: "#00843D",
		colorSecondary: "#F47D31",
		hintRegion: "Southeast",
	},
	{
		name: "University of North Carolina",
		shortName: "North Carolina",
		mascot: "Tar Heels",
		conference: "ACC",
		city: "Chapel Hill",
		state: "NC",
		lat: 35.9064,
		lon: -79.0469,
		colorPrimary: "#4B9CD3",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southeast",
	},
	{
		name: "North Carolina State University",
		shortName: "NC State",
		mascot: "Wolfpack",
		conference: "ACC",
		city: "Raleigh",
		state: "NC",
		lat: 35.7796,
		lon: -78.6382,
		colorPrimary: "#CC0000",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "University of Notre Dame",
		shortName: "Notre Dame",
		mascot: "Fighting Irish",
		conference: "ACC",
		city: "Notre Dame",
		state: "IN",
		lat: 41.7029,
		lon: -86.2394,
		colorPrimary: "#003366",
		colorSecondary: "#FFD700",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Pittsburgh",
		shortName: "Pittsburgh",
		mascot: "Panthers",
		conference: "ACC",
		city: "Pittsburgh",
		state: "PA",
		lat: 40.4426,
		lon: -79.9626,
		colorPrimary: "#003366",
		colorSecondary: "#FFD700",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "Southern Methodist University",
		shortName: "SMU",
		mascot: "Mustangs",
		conference: "ACC",
		city: "Dallas",
		state: "TX",
		lat: 32.8431,
		lon: -96.7816,
		colorPrimary: "#CC0000",
		colorSecondary: "#003366",
		hintRegion: "Southwest",
	},
	{
		name: "Stanford University",
		shortName: "Stanford",
		mascot: "Cardinal",
		conference: "ACC",
		city: "Stanford",
		state: "CA",
		lat: 37.4275,
		lon: -122.1697,
		colorPrimary: "#8B0000",
		colorSecondary: "#FFFFFF",
		hintRegion: "Pacific",
	},
	{
		name: "Syracuse University",
		shortName: "Syracuse",
		mascot: "Orange",
		conference: "ACC",
		city: "Syracuse",
		state: "NY",
		lat: 43.0514,
		lon: -76.1474,
		colorPrimary: "#FF6600",
		colorSecondary: "#003366",
		hintRegion: "Northeast",
	},
	{
		name: "University of Virginia",
		shortName: "Virginia",
		mascot: "Cavaliers",
		conference: "ACC",
		city: "Charlottesville",
		state: "VA",
		lat: 38.0336,
		lon: -78.5080,
		colorPrimary: "#003366",
		colorSecondary: "#FF6600",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "Virginia Polytechnic Institute and State University",
		shortName: "Virginia Tech",
		mascot: "Hokies",
		conference: "ACC",
		city: "Blacksburg",
		state: "VA",
		lat: 37.2296,
		lon: -80.4139,
		colorPrimary: "#8B0000",
		colorSecondary: "#FF8200",
		hintRegion: "Southeast",
	},
	{
		name: "Wake Forest University",
		shortName: "Wake Forest",
		mascot: "Demon Deacons",
		conference: "ACC",
		city: "Winston-Salem",
		state: "NC",
		lat: 36.1326,
		lon: -80.2845,
		colorPrimary: "#000000",
		colorSecondary: "#FFD700",
		colorSwap: true,
		hintRegion: "Southeast",
	},

// AAC - American Athletic Conference (13 schools)
	{
		name: "University of Alabama at Birmingham",
		shortName: "UAB",
		mascot: "Blazers",
		conference: "AAC",
		city: "Birmingham",
		state: "AL",
		lat: 33.5021,
		lon: -86.8114,
		colorPrimary: "#006341",
		colorSecondary: "#CC8A00",
		hintRegion: "Southeast",
	},
	{
		name: "University of North Carolina at Charlotte",
		shortName: "Charlotte",
		mascot: "49ers",
		conference: "AAC",
		city: "Charlotte",
		state: "NC",
		lat: 35.3076,
		lon: -80.7335,
		colorPrimary: "#046A38",
		colorSecondary: "#B9975B",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "East Carolina University",
		shortName: "East Carolina",
		mascot: "Pirates",
		conference: "AAC",
		city: "Greenville",
		state: "NC",
		lat: 35.6087,
		lon: -77.3665,
		colorPrimary: "#592A8A",
		colorSecondary: "#FDC82F",
		hintRegion: "Southeast",
	},
	{
		name: "Florida Atlantic University",
		shortName: "Florida Atlantic",
		mascot: "Owls",
		conference: "AAC",
		city: "Boca Raton",
		state: "FL",
		lat: 26.3713,
		lon: -80.1014,
		colorPrimary: "#003366",
		colorSecondary: "#CC0000",
		hintRegion: "Southeast",
	},
	{
		name: "University of Memphis",
		shortName: "Memphis",
		mascot: "Tigers",
		conference: "AAC",
		city: "Memphis",
		state: "TN",
		lat: 35.1187,
		lon: -89.9378,
		colorPrimary: "#003087",
		colorSecondary: "#898D8D",
		hintRegion: "Southeast",
	},
	{
		name: "University of North Texas",
		shortName: "North Texas",
		mascot: "Mean Green",
		conference: "AAC",
		city: "Denton",
		state: "TX",
		lat: 33.2100,
		lon: -97.1484,
		colorPrimary: "#00853E",
		colorSecondary: "#000000",
		hintRegion: "Southwest",
	},
	{
		name: "Rice University",
		shortName: "Rice",
		mascot: "Owls",
		conference: "AAC",
		city: "Houston",
		state: "TX",
		lat: 29.7174,
		lon: -95.4018,
		colorPrimary: "#00205B",
		colorSecondary: "#C1C6C8",
		hintRegion: "Southwest",
	},
	{
		name: "University of South Florida",
		shortName: "South Florida",
		mascot: "Bulls",
		conference: "AAC",
		city: "Tampa",
		state: "FL",
		lat: 28.0587,
		lon: -82.4139,
		colorPrimary: "#006747",
		colorSecondary: "#CFC493",
		hintRegion: "Southeast",
	},
	{
		name: "Temple University",
		shortName: "Temple",
		mascot: "Owls",
		conference: "AAC",
		city: "Philadelphia",
		state: "PA",
		lat: 39.9813,
		lon: -75.1553,
		colorPrimary: "#9D2235",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "Tulane University",
		shortName: "Tulane",
		mascot: "Green Wave",
		conference: "AAC",
		city: "New Orleans",
		state: "LA",
		lat: 29.9401,
		lon: -90.1205,
		colorPrimary: "#006747",
		colorSecondary: "#418FDE",
		hintRegion: "Southeast",
	},
	{
		name: "University of Tulsa",
		shortName: "Tulsa",
		mascot: "Golden Hurricane",
		conference: "AAC",
		city: "Tulsa",
		state: "OK",
		lat: 36.1527,
		lon: -95.9467,
		colorPrimary: "#00347D",
		colorSecondary: "#EB2A21",
		hintRegion: "Southwest",
	},
	{
		name: "University of Texas at San Antonio",
		shortName: "UTSA",
		mascot: "Roadrunners",
		conference: "AAC",
		city: "San Antonio",
		state: "TX",
		lat: 29.5831,
		lon: -98.6190,
		colorPrimary: "#002A5C",
		colorSecondary: "#F47321",
		hintRegion: "Southwest",
	},
	{
		name: "Wichita State University",
		shortName: "Wichita State",
		mascot: "Shockers",
		conference: "AAC",
		city: "Wichita",
		state: "KS",
		lat: 37.7191,
		lon: -97.2939,
		colorPrimary: "#FFCD00",
		colorSecondary: "#000000",
		hintRegion: "Midwest",
	},

	// Mountain West Conference (12 schools)
	{
		name: "United States Air Force Academy",
		shortName: "Air Force",
		mascot: "Falcons",
		conference: "MWC",
		city: "Colorado Springs",
		state: "CO",
		lat: 38.9983,
		lon: -104.8614,
		colorPrimary: "#003087",
		colorSecondary: "#8A8D8F",
		hintRegion: "Mountain",
	},
	{
		name: "Boise State University",
		shortName: "Boise State",
		mascot: "Broncos",
		conference: "MWC",
		city: "Boise",
		state: "ID",
		lat: 43.6036,
		lon: -116.2049,
		colorPrimary: "#0033A0",
		colorSecondary: "#D64309",
		hintRegion: "Mountain",
	},
	{
		name: "Colorado State University",
		shortName: "Colorado State",
		mascot: "Rams",
		conference: "MWC",
		city: "Fort Collins",
		state: "CO",
		lat: 40.5762,
		lon: -105.0844,
		colorPrimary: "#1E4D2B",
		colorSecondary: "#C8C372",
		hintRegion: "Mountain",
	},
	{
		name: "California State University, Fresno",
		shortName: "Fresno State",
		mascot: "Bulldogs",
		conference: "MWC",
		city: "Fresno",
		state: "CA",
		lat: 36.8117,
		lon: -119.7481,
		colorPrimary: "#DB0032",
		colorSecondary: "#002E6D",
		hintRegion: "Pacific",
	},
	{
		name: "Grand Canyon University",
		shortName: "Grand Canyon",
		mascot: "Antelopes",
		conference: "MWC",
		city: "Phoenix",
		state: "AZ",
		lat: 33.5088,
		lon: -112.1258,
		colorPrimary: "#522D80",
		colorSecondary: "#000000",
		hintRegion: "Southwest",
	},
	{
		name: "University of Nevada, Reno",
		shortName: "Nevada",
		mascot: "Wolf Pack",
		conference: "MWC",
		city: "Reno",
		state: "NV",
		lat: 39.5440,
		lon: -119.8168,
		colorPrimary: "#003366",
		colorSecondary: "#C0C0C0",
		hintRegion: "Mountain",
	},
	{
		name: "University of New Mexico",
		shortName: "New Mexico",
		mascot: "Lobos",
		conference: "MWC",
		city: "Albuquerque",
		state: "NM",
		lat: 35.0844,
		lon: -106.6189,
		colorPrimary: "#BA0C2F",
		colorSecondary: "#A7A8AA",
		hintRegion: "Southwest",
	},
	{
		name: "San Diego State University",
		shortName: "San Diego State",
		mascot: "Aztecs",
		conference: "MWC",
		city: "San Diego",
		state: "CA",
		lat: 32.7757,
		lon: -117.0719,
		colorPrimary: "#A6192E",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Pacific",
	},
	{
		name: "San Jose State University",
		shortName: "San Jose State",
		mascot: "Spartans",
		conference: "MWC",
		city: "San Jose",
		state: "CA",
		lat: 37.3361,
		lon: -121.8819,
		colorPrimary: "#0055A2",
		colorSecondary: "#E5A823",
		hintRegion: "Pacific",
	},
	{
		name: "University of Nevada, Las Vegas",
		shortName: "UNLV",
		mascot: "Rebels",
		conference: "MWC",
		city: "Las Vegas",
		state: "NV",
		lat: 36.1085,
		lon: -115.1440,
		colorPrimary: "#CF0A2C",
		colorSecondary: "#666666",
		hintRegion: "Mountain",
	},
	{
		name: "Utah State University",
		shortName: "Utah State",
		mascot: "Aggies",
		conference: "MWC",
		city: "Logan",
		state: "UT",
		lat: 41.7450,
		lon: -111.8097,
		colorPrimary: "#0F2439",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Mountain",
	},
	{
		name: "University of Wyoming",
		shortName: "Wyoming",
		mascot: "Cowboys",
		conference: "MWC",
		city: "Laramie",
		state: "WY",
		lat: 41.3149,
		lon: -105.5670,
		colorPrimary: "#492F24",
		colorSecondary: "#FFC425",
		hintRegion: "Mountain",
	},

	// Atlantic 10 Conference (14 schools)
	{
		name: "Davidson College",
		shortName: "Davidson",
		mascot: "Wildcats",
		conference: "A-10",
		city: "Davidson",
		state: "NC",
		lat: 35.4993,
		lon: -80.8487,
		colorPrimary: "#AC1A2F",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "University of Dayton",
		shortName: "Dayton",
		mascot: "Flyers",
		conference: "A-10",
		city: "Dayton",
		state: "OH",
		lat: 39.7411,
		lon: -84.1799,
		colorPrimary: "#CE1141",
		colorSecondary: "#004B8D",
		hintRegion: "Midwest",
	},
	{
		name: "Duquesne University",
		shortName: "Duquesne",
		mascot: "Dukes",
		conference: "A-10",
		city: "Pittsburgh",
		state: "PA",
		lat: 40.4366,
		lon: -79.9930,
		colorPrimary: "#002D62",
		colorSecondary: "#BA0C2F",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "Fordham University",
		shortName: "Fordham",
		mascot: "Rams",
		conference: "A-10",
		city: "Bronx",
		state: "NY",
		lat: 40.8613,
		lon: -73.8856,
		colorPrimary: "#6E0A1E",
		colorSecondary: "#FFFFFF",
		hintRegion: "Northeast",
	},
	{
		name: "George Mason University",
		shortName: "George Mason",
		mascot: "Patriots",
		conference: "A-10",
		city: "Fairfax",
		state: "VA",
		lat: 38.8325,
		lon: -77.3073,
		colorPrimary: "#006633",
		colorSecondary: "#FFCC33",
		hintRegion: "Southeast",
	},
	{
		name: "George Washington University",
		shortName: "George Washington",
		mascot: "Revolutionaries",
		conference: "A-10",
		city: "Washington",
		state: "DC",
		lat: 38.8997,
		lon: -77.0489,
		colorPrimary: "#033C5A",
		colorSecondary: "#AA9868",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "La Salle University",
		shortName: "La Salle",
		mascot: "Explorers",
		conference: "A-10",
		city: "Philadelphia",
		state: "PA",
		lat: 40.0382,
		lon: -75.1555,
		colorPrimary: "#002B5C",
		colorSecondary: "#BF9B30",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "Loyola University Chicago",
		shortName: "Loyola Chicago",
		mascot: "Ramblers",
		conference: "A-10",
		city: "Chicago",
		state: "IL",
		lat: 41.9990,
		lon: -87.6586,
		colorPrimary: "#6C1D45",
		colorSecondary: "#D4A843",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Rhode Island",
		shortName: "Rhode Island",
		mascot: "Rams",
		conference: "A-10",
		city: "Kingston",
		state: "RI",
		lat: 41.4833,
		lon: -71.5246,
		colorPrimary: "#002147",
		colorSecondary: "#75B2DD",
		hintRegion: "Northeast",
	},
	{
		name: "University of Richmond",
		shortName: "Richmond",
		mascot: "Spiders",
		conference: "A-10",
		city: "Richmond",
		state: "VA",
		lat: 37.5741,
		lon: -77.5413,
		colorPrimary: "#000066",
		colorSecondary: "#990000",
		hintRegion: "Southeast",
	},
	{
		name: "Saint Bonaventure University",
		shortName: "St. Bonaventure",
		mascot: "Bonnies",
		conference: "A-10",
		city: "Allegany",
		state: "NY",
		lat: 42.0810,
		lon: -78.4748,
		colorPrimary: "#6B3529",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "Saint Joseph's University",
		shortName: "Saint Joseph's",
		mascot: "Hawks",
		conference: "A-10",
		city: "Philadelphia",
		state: "PA",
		lat: 39.9975,
		lon: -75.2389,
		colorPrimary: "#9E1B34",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "Saint Louis University",
		shortName: "Saint Louis",
		mascot: "Billikens",
		conference: "A-10",
		city: "St. Louis",
		state: "MO",
		lat: 38.6351,
		lon: -90.2340,
		colorPrimary: "#003DA5",
		colorSecondary: "#C8C9C7",
		hintRegion: "Midwest",
	},
	{
		name: "Virginia Commonwealth University",
		shortName: "VCU",
		mascot: "Rams",
		conference: "A-10",
		city: "Richmond",
		state: "VA",
		lat: 37.5497,
		lon: -77.4527,
		colorPrimary: "#FFB300",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Southeast",
	},

	// West Coast Conference (12 schools)
	{
		name: "Gonzaga University",
		shortName: "Gonzaga",
		mascot: "Bulldogs",
		conference: "WCC",
		city: "Spokane",
		state: "WA",
		lat: 47.6672,
		lon: -117.4017,
		colorPrimary: "#041E42",
		colorSecondary: "#C8102E",
		hintRegion: "Pacific",
	},
	{
		name: "Loyola Marymount University",
		shortName: "Loyola Marymount",
		mascot: "Lions",
		conference: "WCC",
		city: "Los Angeles",
		state: "CA",
		lat: 33.9700,
		lon: -118.4175,
		colorPrimary: "#00345B",
		colorSecondary: "#8B2332",
		hintRegion: "Pacific",
	},
	{
		name: "Oregon State University",
		shortName: "Oregon State",
		mascot: "Beavers",
		conference: "WCC",
		city: "Corvallis",
		state: "OR",
		lat: 44.5638,
		lon: -123.2794,
		colorPrimary: "#DC4405",
		colorSecondary: "#000000",
		hintRegion: "Pacific",
	},
	{
		name: "University of the Pacific",
		shortName: "Pacific",
		mascot: "Tigers",
		conference: "WCC",
		city: "Stockton",
		state: "CA",
		lat: 37.9793,
		lon: -121.3115,
		colorPrimary: "#F47920",
		colorSecondary: "#000000",
		hintRegion: "Pacific",
	},
	{
		name: "Pepperdine University",
		shortName: "Pepperdine",
		mascot: "Waves",
		conference: "WCC",
		city: "Malibu",
		state: "CA",
		lat: 34.0396,
		lon: -118.7067,
		colorPrimary: "#003A63",
		colorSecondary: "#E35205",
		colorSwap: true,
		hintRegion: "Pacific",
	},
	{
		name: "University of Portland",
		shortName: "Portland",
		mascot: "Pilots",
		conference: "WCC",
		city: "Portland",
		state: "OR",
		lat: 45.5640,
		lon: -122.7263,
		colorPrimary: "#3E1f71",
		colorSecondary: "#FFFFFF",
		hintRegion: "Pacific",
	},
	{
		name: "Saint Mary's College of California",
		shortName: "Saint Mary's",
		mascot: "Gaels",
		conference: "WCC",
		city: "Moraga",
		state: "CA",
		lat: 37.8406,
		lon: -122.1139,
		colorPrimary: "#003DA5",
		colorSecondary: "#CE1141",
		hintRegion: "Pacific",
	},
	{
		name: "University of San Diego",
		shortName: "San Diego",
		mascot: "Toreros",
		conference: "WCC",
		city: "San Diego",
		state: "CA",
		lat: 32.7716,
		lon: -117.1888,
		colorPrimary: "#002B5C",
		colorSecondary: "#A7C6ED",
		hintRegion: "Pacific",
	},
	{
		name: "University of San Francisco",
		shortName: "San Francisco",
		mascot: "Dons",
		conference: "WCC",
		city: "San Francisco",
		state: "CA",
		lat: 37.7765,
		lon: -122.4510,
		colorPrimary: "#006747",
		colorSecondary: "#FDBB30",
		hintRegion: "Pacific",
	},
	{
		name: "Santa Clara University",
		shortName: "Santa Clara",
		mascot: "Broncos",
		conference: "WCC",
		city: "Santa Clara",
		state: "CA",
		lat: 37.3496,
		lon: -121.9381,
		colorPrimary: "#862633",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Pacific",
	},
	{
		name: "Seattle University",
		shortName: "Seattle",
		mascot: "Redhawks",
		conference: "WCC",
		city: "Seattle",
		state: "WA",
		lat: 47.6102,
		lon: -122.3190,
		colorPrimary: "#AA0000",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Pacific",
	},
	{
		name: "Washington State University",
		shortName: "Washington State",
		mascot: "Cougars",
		conference: "WCC",
		city: "Pullman",
		state: "WA",
		lat: 46.7319,
		lon: -117.1542,
		colorPrimary: "#981E32",
		colorSecondary: "#5E6A71",
		hintRegion: "Pacific",
	},

	// Missouri Valley Conference (11 schools)
	{
		name: "Belmont University",
		shortName: "Belmont",
		mascot: "Bruins",
		conference: "MVC",
		city: "Nashville",
		state: "TN",
		lat: 36.1324,
		lon: -86.7930,
		colorPrimary: "#002B5C",
		colorSecondary: "#C41230",
		hintRegion: "Southeast",
	},
	{
		name: "Bradley University",
		shortName: "Bradley",
		mascot: "Braves",
		conference: "MVC",
		city: "Peoria",
		state: "IL",
		lat: 40.6988,
		lon: -89.6165,
		colorPrimary: "#AC1A2F",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Drake University",
		shortName: "Drake",
		mascot: "Bulldogs",
		conference: "MVC",
		city: "Des Moines",
		state: "IA",
		lat: 41.6044,
		lon: -93.6527,
		colorPrimary: "#003B71",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Evansville",
		shortName: "Evansville",
		mascot: "Purple Aces",
		conference: "MVC",
		city: "Evansville",
		state: "IN",
		lat: 37.9688,
		lon: -87.5315,
		colorPrimary: "#400080",
		colorSecondary: "#F36F21",
		hintRegion: "Midwest",
	},
	{
		name: "Illinois State University",
		shortName: "Illinois State",
		mascot: "Redbirds",
		conference: "MVC",
		city: "Normal",
		state: "IL",
		lat: 40.5106,
		lon: -88.9981,
		colorPrimary: "#CE1126",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Indiana State University",
		shortName: "Indiana State",
		mascot: "Sycamores",
		conference: "MVC",
		city: "Terre Haute",
		state: "IN",
		lat: 39.4688,
		lon: -87.4071,
		colorPrimary: "#003B71",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Murray State University",
		shortName: "Murray State",
		mascot: "Racers",
		conference: "MVC",
		city: "Murray",
		state: "KY",
		lat: 36.6132,
		lon: -88.3174,
		colorPrimary: "#002144",
		colorSecondary: "#D4A843",
		hintRegion: "Southeast",
	},
	{
		name: "University of Northern Iowa",
		shortName: "Northern Iowa",
		mascot: "Panthers",
		conference: "MVC",
		city: "Cedar Falls",
		state: "IA",
		lat: 42.5139,
		lon: -92.4588,
		colorPrimary: "#4B116F",
		colorSecondary: "#FFCC00",
		hintRegion: "Midwest",
	},
	{
		name: "Southern Illinois University",
		shortName: "Southern Illinois",
		mascot: "Salukis",
		conference: "MVC",
		city: "Carbondale",
		state: "IL",
		lat: 37.7158,
		lon: -89.2168,
		colorPrimary: "#6E0A1E",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Illinois Chicago",
		shortName: "UIC",
		mascot: "Flames",
		conference: "MVC",
		city: "Chicago",
		state: "IL",
		lat: 41.8703,
		lon: -87.6499,
		colorPrimary: "#001E62",
		colorSecondary: "#D50032",
		hintRegion: "Midwest",
	},
	{
		name: "Valparaiso University",
		shortName: "Valparaiso",
		mascot: "Beacons",
		conference: "MVC",
		city: "Valparaiso",
		state: "IN",
		lat: 41.4631,
		lon: -87.0352,
		colorPrimary: "#613318",
		colorSecondary: "#FDBB30",
		colorSwap: true,
		hintRegion: "Midwest",
	},

	// Conference USA (12 schools)
	{
		name: "University of Delaware",
		shortName: "Delaware",
		mascot: "Blue Hens",
		conference: "C-USA",
		city: "Newark",
		state: "DE",
		lat: 39.6800,
		lon: -75.7523,
		colorPrimary: "#003366",
		colorSecondary: "#FFD200",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "Florida International University",
		shortName: "FIU",
		mascot: "Panthers",
		conference: "C-USA",
		city: "Miami",
		state: "FL",
		lat: 25.7564,
		lon: -80.3736,
		colorPrimary: "#002F56",
		colorSecondary: "#B6862C",
		hintRegion: "Southeast",
	},
	{
		name: "Jacksonville State University",
		shortName: "Jacksonville State",
		mascot: "Gamecocks",
		conference: "C-USA",
		city: "Jacksonville",
		state: "AL",
		lat: 33.8201,
		lon: -85.7644,
		colorPrimary: "#CC0000",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southeast",
	},
	{
		name: "Kennesaw State University",
		shortName: "Kennesaw State",
		mascot: "Owls",
		conference: "C-USA",
		city: "Kennesaw",
		state: "GA",
		lat: 34.0392,
		lon: -84.5826,
		colorPrimary: "#000000",
		colorSecondary: "#FDBB30",
		hintRegion: "Southeast",
	},
	{
		name: "Liberty University",
		shortName: "Liberty",
		mascot: "Flames",
		conference: "C-USA",
		city: "Lynchburg",
		state: "VA",
		lat: 37.3530,
		lon: -79.1724,
		colorPrimary: "#002D62",
		colorSecondary: "#C41230",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "Louisiana Tech University",
		shortName: "Louisiana Tech",
		mascot: "Bulldogs",
		conference: "C-USA",
		city: "Ruston",
		state: "LA",
		lat: 32.5259,
		lon: -92.6468,
		colorPrimary: "#002F8B",
		colorSecondary: "#CF202E",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "Middle Tennessee State University",
		shortName: "Middle Tennessee",
		mascot: "Blue Raiders",
		conference: "C-USA",
		city: "Murfreesboro",
		state: "TN",
		lat: 35.8489,
		lon: -86.3679,
		colorPrimary: "#0066CC",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southeast",
	},
	{
		name: "Missouri State University",
		shortName: "Missouri State",
		mascot: "Bears",
		conference: "C-USA",
		city: "Springfield",
		state: "MO",
		lat: 37.2057,
		lon: -93.2819,
		colorPrimary: "#6A0032",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "New Mexico State University",
		shortName: "New Mexico State",
		mascot: "Aggies",
		conference: "C-USA",
		city: "Las Cruces",
		state: "NM",
		lat: 32.2802,
		lon: -106.7474,
		colorPrimary: "#891216",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southwest",
	},
	{
		name: "Sam Houston State University",
		shortName: "Sam Houston",
		mascot: "Bearkats",
		conference: "C-USA",
		city: "Huntsville",
		state: "TX",
		lat: 30.7153,
		lon: -95.5515,
		colorPrimary: "#F47321",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Southwest",
	},
	{
		name: "University of Texas at El Paso",
		shortName: "UTEP",
		mascot: "Miners",
		conference: "C-USA",
		city: "El Paso",
		state: "TX",
		lat: 31.7707,
		lon: -106.5047,
		colorPrimary: "#FF8200",
		colorSecondary: "#041E42",
		hintRegion: "Southwest",
	},
	{
		name: "Western Kentucky University",
		shortName: "Western Kentucky",
		mascot: "Hilltoppers",
		conference: "C-USA",
		city: "Bowling Green",
		state: "KY",
		lat: 36.9864,
		lon: -86.4563,
		colorPrimary: "#B01E24",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Southeast",
	},

	// Sun Belt Conference (14 schools)
	{
		name: "Appalachian State University",
		shortName: "Appalachian State",
		mascot: "Mountaineers",
		conference: "Sun Belt",
		city: "Boone",
		state: "NC",
		lat: 36.2134,
		lon: -81.6878,
		colorPrimary: "#000000",
		colorSecondary: "#FFCC00",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "Arkansas State University",
		shortName: "Arkansas State",
		mascot: "Red Wolves",
		conference: "Sun Belt",
		city: "Jonesboro",
		state: "AR",
		lat: 35.8445,
		lon: -90.6816,
		colorPrimary: "#CC092F",
		colorSecondary: "#000000",
		hintRegion: "Southeast",
	},
	{
		name: "Coastal Carolina University",
		shortName: "Coastal Carolina",
		mascot: "Chanticleers",
		conference: "Sun Belt",
		city: "Conway",
		state: "SC",
		lat: 33.7949,
		lon: -79.0195,
		colorPrimary: "#006F71",
		colorSecondary: "#A27752",
		hintRegion: "Southeast",
	},
	{
		name: "Georgia Southern University",
		shortName: "Georgia Southern",
		mascot: "Eagles",
		conference: "Sun Belt",
		city: "Statesboro",
		state: "GA",
		lat: 32.4226,
		lon: -81.7837,
		colorPrimary: "#011E41",
		colorSecondary: "#87714D",
		hintRegion: "Southeast",
	},
	{
		name: "Georgia State University",
		shortName: "Georgia State",
		mascot: "Panthers",
		conference: "Sun Belt",
		city: "Atlanta",
		state: "GA",
		lat: 33.7530,
		lon: -84.3861,
		colorPrimary: "#0039A6",
		colorSecondary: "#CC0000",
		hintRegion: "Southeast",
	},
	{
		name: "James Madison University",
		shortName: "James Madison",
		mascot: "Dukes",
		conference: "Sun Belt",
		city: "Harrisonburg",
		state: "VA",
		lat: 38.4362,
		lon: -78.8698,
		colorPrimary: "#450084",
		colorSecondary: "#CBB677",
		hintRegion: "Southeast",
	},
	{
		name: "University of Louisiana at Lafayette",
		shortName: "Louisiana",
		mascot: "Ragin' Cajuns",
		conference: "Sun Belt",
		city: "Lafayette",
		state: "LA",
		lat: 30.2133,
		lon: -92.0190,
		colorPrimary: "#CE181E",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southeast",
	},
	{
		name: "University of Louisiana at Monroe",
		shortName: "UL Monroe",
		mascot: "Warhawks",
		conference: "Sun Belt",
		city: "Monroe",
		state: "LA",
		lat: 32.5279,
		lon: -92.0762,
		colorPrimary: "#6A0032",
		colorSecondary: "#FDBB30",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "Marshall University",
		shortName: "Marshall",
		mascot: "Thundering Herd",
		conference: "Sun Belt",
		city: "Huntington",
		state: "WV",
		lat: 38.4250,
		lon: -82.4267,
		colorPrimary: "#00B140",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "Old Dominion University",
		shortName: "Old Dominion",
		mascot: "Monarchs",
		conference: "Sun Belt",
		city: "Norfolk",
		state: "VA",
		lat: 36.8853,
		lon: -76.3060,
		colorPrimary: "#003057",
		colorSecondary: "#7C878E",
		hintRegion: "Southeast",
	},
	{
		name: "University of South Alabama",
		shortName: "South Alabama",
		mascot: "Jaguars",
		conference: "Sun Belt",
		city: "Mobile",
		state: "AL",
		lat: 30.6955,
		lon: -88.1783,
		colorPrimary: "#003E7E",
		colorSecondary: "#CC0000",
		hintRegion: "Southeast",
	},
	{
		name: "University of Southern Mississippi",
		shortName: "Southern Miss",
		mascot: "Golden Eagles",
		conference: "Sun Belt",
		city: "Hattiesburg",
		state: "MS",
		lat: 31.3289,
		lon: -89.3358,
		colorPrimary: "#000000",
		colorSecondary: "#FFB81C",
		hintRegion: "Southeast",
	},
	{
		name: "Texas State University",
		shortName: "Texas State",
		mascot: "Bobcats",
		conference: "Sun Belt",
		city: "San Marcos",
		state: "TX",
		lat: 29.8885,
		lon: -97.9380,
		colorPrimary: "#501214",
		colorSecondary: "#8D734A",
		hintRegion: "Southwest",
	},
	{
		name: "Troy University",
		shortName: "Troy",
		mascot: "Trojans",
		conference: "Sun Belt",
		city: "Troy",
		state: "AL",
		lat: 31.7988,
		lon: -85.9694,
		colorPrimary: "#8B2332",
		colorSecondary: "#000000",
		hintRegion: "Southeast",
	},

	// Mid-American Conference (14 schools)
	{
		name: "University of Akron",
		shortName: "Akron",
		mascot: "Zips",
		conference: "MAC",
		city: "Akron",
		state: "OH",
		lat: 41.0768,
		lon: -81.5121,
		colorPrimary: "#002147",
		colorSecondary: "#C99700",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Ball State University",
		shortName: "Ball State",
		mascot: "Cardinals",
		conference: "MAC",
		city: "Muncie",
		state: "IN",
		lat: 40.2052,
		lon: -85.4086,
		colorPrimary: "#BA0C2F",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Bowling Green State University",
		shortName: "Bowling Green",
		mascot: "Falcons",
		conference: "MAC",
		city: "Bowling Green",
		state: "OH",
		lat: 41.3786,
		lon: -83.6237,
		colorPrimary: "#4F2C1D",
		colorSecondary: "#FF7300",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University at Buffalo",
		shortName: "Buffalo",
		mascot: "Bulls",
		conference: "MAC",
		city: "Buffalo",
		state: "NY",
		lat: 43.0008,
		lon: -78.7890,
		colorPrimary: "#005BBB",
		colorSecondary: "#FFFFFF",
		hintRegion: "Northeast",
	},
	{
		name: "Central Michigan University",
		shortName: "Central Michigan",
		mascot: "Chippewas",
		conference: "MAC",
		city: "Mount Pleasant",
		state: "MI",
		lat: 43.5936,
		lon: -84.7678,
		colorPrimary: "#6A0032",
		colorSecondary: "#FFC82E",
		hintRegion: "Midwest",
	},
	{
		name: "Eastern Michigan University",
		shortName: "Eastern Michigan",
		mascot: "Eagles",
		conference: "MAC",
		city: "Ypsilanti",
		state: "MI",
		lat: 42.2504,
		lon: -83.6238,
		colorPrimary: "#006633",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Kent State University",
		shortName: "Kent State",
		mascot: "Golden Flashes",
		conference: "MAC",
		city: "Kent",
		state: "OH",
		lat: 41.1453,
		lon: -81.3421,
		colorPrimary: "#002664",
		colorSecondary: "#EAAB00",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Miami University",
		shortName: "Miami (OH)",
		mascot: "RedHawks",
		conference: "MAC",
		city: "Oxford",
		state: "OH",
		lat: 39.5100,
		lon: -84.7340,
		colorPrimary: "#B61E2E",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Northern Illinois University",
		shortName: "Northern Illinois",
		mascot: "Huskies",
		conference: "MAC",
		city: "DeKalb",
		state: "IL",
		lat: 41.9345,
		lon: -88.7700,
		colorPrimary: "#BA0C2F",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Ohio University",
		shortName: "Ohio",
		mascot: "Bobcats",
		conference: "MAC",
		city: "Athens",
		state: "OH",
		lat: 39.3238,
		lon: -82.1013,
		colorPrimary: "#00694E",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Toledo",
		shortName: "Toledo",
		mascot: "Rockets",
		conference: "MAC",
		city: "Toledo",
		state: "OH",
		lat: 41.6579,
		lon: -83.6152,
		colorPrimary: "#003C71",
		colorSecondary: "#EAAB00",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Massachusetts",
		shortName: "UMass",
		mascot: "Minutemen",
		conference: "MAC",
		city: "Amherst",
		state: "MA",
		lat: 42.3868,
		lon: -72.5301,
		colorPrimary: "#881C1C",
		colorSecondary: "#000000",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "Western Michigan University",
		shortName: "Western Michigan",
		mascot: "Broncos",
		conference: "MAC",
		city: "Kalamazoo",
		state: "MI",
		lat: 42.2828,
		lon: -85.6118,
		colorPrimary: "#6C4023",
		colorSecondary: "#B5A167",
		colorSwap: true,
		hintRegion: "Midwest",
	},

	// Colonial Athletic Association (13 schools)
	{
		name: "Campbell University",
		shortName: "Campbell",
		mascot: "Fighting Camels",
		conference: "CAA",
		city: "Buies Creek",
		state: "NC",
		lat: 35.4103,
		lon: -78.7387,
		colorPrimary: "#F47321",
		colorSecondary: "#000000",
		hintRegion: "Southeast",
	},
	{
		name: "College of Charleston",
		shortName: "Charleston",
		mascot: "Cougars",
		conference: "CAA",
		city: "Charleston",
		state: "SC",
		lat: 32.7835,
		lon: -79.9365,
		colorPrimary: "#6A0032",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southeast",
	},
	{
		name: "Drexel University",
		shortName: "Drexel",
		mascot: "Dragons",
		conference: "CAA",
		city: "Philadelphia",
		state: "PA",
		lat: 39.9566,
		lon: -75.1899,
		colorPrimary: "#002C5F",
		colorSecondary: "#FFC600",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "Elon University",
		shortName: "Elon",
		mascot: "Phoenix",
		conference: "CAA",
		city: "Elon",
		state: "NC",
		lat: 36.1033,
		lon: -79.5023,
		colorPrimary: "#6A0032",
		colorSecondary: "#B39F6B",
		hintRegion: "Southeast",
	},
	{
		name: "Hampton University",
		shortName: "Hampton",
		mascot: "Pirates",
		conference: "CAA",
		city: "Hampton",
		state: "VA",
		lat: 37.0229,
		lon: -76.3360,
		colorPrimary: "#003087",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "Hofstra University",
		shortName: "Hofstra",
		mascot: "Pride",
		conference: "CAA",
		city: "Hempstead",
		state: "NY",
		lat: 40.7141,
		lon: -73.5997,
		colorPrimary: "#003591",
		colorSecondary: "#FFD200",
		hintRegion: "Northeast",
	},
	{
		name: "Monmouth University",
		shortName: "Monmouth",
		mascot: "Hawks",
		conference: "CAA",
		city: "West Long Branch",
		state: "NJ",
		lat: 40.2773,
		lon: -74.0054,
		colorPrimary: "#003DA5",
		colorSecondary: "#A2AAAD",
		hintRegion: "Northeast",
	},
	{
		name: "North Carolina A&T State University",
		shortName: "NC A&T",
		mascot: "Aggies",
		conference: "CAA",
		city: "Greensboro",
		state: "NC",
		lat: 36.0720,
		lon: -79.7738,
		colorPrimary: "#003087",
		colorSecondary: "#CFB53B",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "Northeastern University",
		shortName: "Northeastern",
		mascot: "Huskies",
		conference: "CAA",
		city: "Boston",
		state: "MA",
		lat: 42.3398,
		lon: -71.0892,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		hintRegion: "Northeast",
	},
	{
		name: "Stony Brook University",
		shortName: "Stony Brook",
		mascot: "Seawolves",
		conference: "CAA",
		city: "Stony Brook",
		state: "NY",
		lat: 40.9128,
		lon: -73.1235,
		colorPrimary: "#CC0000",
		colorSecondary: "#003DA5",
		hintRegion: "Northeast",
	},
	{
		name: "Towson University",
		shortName: "Towson",
		mascot: "Tigers",
		conference: "CAA",
		city: "Towson",
		state: "MD",
		lat: 39.3936,
		lon: -76.6094,
		colorPrimary: "#000000",
		colorSecondary: "#FFB81C",
		hintRegion: "Northeast",
	},
	{
		name: "University of North Carolina Wilmington",
		shortName: "UNCW",
		mascot: "Seahawks",
		conference: "CAA",
		city: "Wilmington",
		state: "NC",
		lat: 34.2274,
		lon: -77.8726,
		colorPrimary: "#006666",
		colorSecondary: "#FDBB30",
		hintRegion: "Southeast",
	},
	{
		name: "College of William & Mary",
		shortName: "William & Mary",
		mascot: "Tribe",
		conference: "CAA",
		city: "Williamsburg",
		state: "VA",
		lat: 37.2707,
		lon: -76.7130,
		colorPrimary: "#115740",
		colorSecondary: "#B0B7BC",
		hintRegion: "Southeast",
	},

	// Horizon League (11 schools)
	{
		name: "Cleveland State University",
		shortName: "Cleveland State",
		mascot: "Vikings",
		conference: "Horizon",
		city: "Cleveland",
		state: "OH",
		lat: 41.5019,
		lon: -81.6745,
		colorPrimary: "#006338",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Detroit Mercy",
		shortName: "Detroit Mercy",
		mascot: "Titans",
		conference: "Horizon",
		city: "Detroit",
		state: "MI",
		lat: 42.3518,
		lon: -83.0679,
		colorPrimary: "#002D62",
		colorSecondary: "#CE1141",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Wisconsin-Green Bay",
		shortName: "Green Bay",
		mascot: "Phoenix",
		conference: "Horizon",
		city: "Green Bay",
		state: "WI",
		lat: 44.5311,
		lon: -87.9003,
		colorPrimary: "#006747",
		colorSecondary: "#FFFFFF",
		hintRegion: "Midwest",
	},
	{
		name: "Indiana University Indianapolis",
		shortName: "IU Indianapolis",
		mascot: "Jaguars",
		conference: "Horizon",
		city: "Indianapolis",
		state: "IN",
		lat: 39.7741,
		lon: -86.1761,
		colorPrimary: "#990000",
		colorSecondary: "#FFCC00",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "University of Wisconsin-Milwaukee",
		shortName: "Milwaukee",
		mascot: "Panthers",
		conference: "Horizon",
		city: "Milwaukee",
		state: "WI",
		lat: 43.0782,
		lon: -87.8817,
		colorPrimary: "#000000",
		colorSecondary: "#FFB81C",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Northern Kentucky University",
		shortName: "Northern Kentucky",
		mascot: "Norse",
		conference: "Horizon",
		city: "Highland Heights",
		state: "KY",
		lat: 39.0325,
		lon: -84.4641,
		colorPrimary: "#000000",
		colorSecondary: "#F7C843",
		colorSwap: true,
		hintRegion: "Southeast",
	},
	{
		name: "Oakland University",
		shortName: "Oakland",
		mascot: "Golden Grizzlies",
		conference: "Horizon",
		city: "Rochester",
		state: "MI",
		lat: 42.6735,
		lon: -83.2173,
		colorPrimary: "#000000",
		colorSecondary: "#B89966",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Purdue University Fort Wayne",
		shortName: "Purdue Fort Wayne",
		mascot: "Mastodons",
		conference: "Horizon",
		city: "Fort Wayne",
		state: "IN",
		lat: 41.1149,
		lon: -85.1110,
		colorPrimary: "#000000",
		colorSecondary: "#CFB991",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Robert Morris University",
		shortName: "Robert Morris",
		mascot: "Colonials",
		conference: "Horizon",
		city: "Moon Township",
		state: "PA",
		lat: 40.5195,
		lon: -80.1687,
		colorPrimary: "#002147",
		colorSecondary: "#CC0000",
		colorSwap: true,
		hintRegion: "Northeast",
	},
	{
		name: "Wright State University",
		shortName: "Wright State",
		mascot: "Raiders",
		conference: "Horizon",
		city: "Dayton",
		state: "OH",
		lat: 39.7824,
		lon: -84.0616,
		colorPrimary: "#007A33",
		colorSecondary: "#FFCD00",
		colorSwap: true,
		hintRegion: "Midwest",
	},
	{
		name: "Youngstown State University",
		shortName: "Youngstown State",
		mascot: "Penguins",
		conference: "Horizon",
		city: "Youngstown",
		state: "OH",
		lat: 41.1054,
		lon: -80.6460,
		colorPrimary: "#CC0000",
		colorSecondary: "#FFFFFF",
		colorSwap: true,
		hintRegion: "Midwest",
	},

];

// Conference tier definitions for the setup screen
var CONFERENCE_TIERS = [
	{
		name: "Power Conferences",
		conferences: ["SEC", "Big Ten", "Big 12", "ACC"],
	},
	{
		name: "Mid-Major Conferences",
		conferences: ["AAC", "MWC", "A-10", "WCC", "MVC", "C-USA", "Sun Belt", "MAC", "CAA", "Horizon"],
	},
];

var SUBREGIONS = {
	"Northeast": ["ME","NH","VT","MA","RI","CT","NY","NJ","PA","MD","DE","DC"],
	"Southeast": ["VA","WV","NC","SC","GA","FL","AL","MS","TN","KY","LA","AR"],
	"Midwest": ["OH","IN","IL","MI","WI","MN","IA","MO","ND","SD","NE","KS"],
	"Southwest": ["TX","OK","NM","AZ"],
	"Mountain": ["CO","UT","WY","MT","ID","NV"],
	"Pacific": ["WA","OR","CA"],
};
