// NCAA Power Conference Schools - 2025-2026 realignment

var NCAA_SCHOOLS = [
	// SEC (16 schools)
	{
		name: "University of Alabama",
		shortName: "Alabama",
		mascot: "Crimson Tide",
		conference: "SEC",
		city: "Tuscaloosa",
		state: "AL",
		lat: 33.2098,
		lon: -87.5692,
		colorPrimary: "#9E1B32",
		colorSecondary: "#828A8F",
		hintRegion: "Southeast",
	},
	{
		name: "University of Arkansas",
		shortName: "Arkansas",
		mascot: "Razorbacks",
		conference: "SEC",
		city: "Fayetteville",
		state: "AR",
		lat: 36.0726,
		lon: -94.1732,
		colorPrimary: "#C4243E",
		colorSecondary: "#F1E4DE",
		hintRegion: "Southeast",
	},
	{
		name: "Auburn University",
		shortName: "Auburn",
		mascot: "Tigers",
		conference: "SEC",
		city: "Auburn",
		state: "AL",
		lat: 32.6024,
		lon: -85.4870,
		colorPrimary: "#FF6600",
		colorSecondary: "#003366",
		hintRegion: "Southeast",
	},
	{
		name: "University of Florida",
		shortName: "Florida",
		mascot: "Gators",
		conference: "SEC",
		city: "Gainesville",
		state: "FL",
		lat: 29.6436,
		lon: -82.3549,
		colorPrimary: "#0033CC",
		colorSecondary: "#FF6600",
		hintRegion: "Southeast",
	},
	{
		name: "University of Georgia",
		shortName: "Georgia",
		mascot: "Bulldogs",
		conference: "SEC",
		city: "Athens",
		state: "GA",
		lat: 33.9519,
		lon: -83.3576,
		colorPrimary: "#BA0021",
		colorSecondary: "#000000",
		hintRegion: "Southeast",
	},
	{
		name: "University of Kentucky",
		shortName: "Kentucky",
		mascot: "Wildcats",
		conference: "SEC",
		city: "Lexington",
		state: "KY",
		lat: 38.0304,
		lon: -84.4699,
		colorPrimary: "#003366",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southeast",
	},
	{
		name: "Louisiana State University",
		shortName: "LSU",
		mascot: "Tigers",
		conference: "SEC",
		city: "Baton Rouge",
		state: "LA",
		lat: 30.4130,
		lon: -91.1871,
		colorPrimary: "#461D7C",
		colorSecondary: "#FDD835",
		hintRegion: "Southeast",
	},
	{
		name: "University of Mississippi",
		shortName: "Ole Miss",
		mascot: "Rebels",
		conference: "SEC",
		city: "Oxford",
		state: "MS",
		lat: 34.3642,
		lon: -89.5344,
		colorPrimary: "#DC143C",
		colorSecondary: "#003478",
		hintRegion: "Southeast",
	},
	{
		name: "Mississippi State University",
		shortName: "Mississippi State",
		mascot: "Bulldogs",
		conference: "SEC",
		city: "Starkville",
		state: "MS",
		lat: 33.4549,
		lon: -88.7903,
		colorPrimary: "#660033",
		colorSecondary: "#FFCC00",
		hintRegion: "Southeast",
	},
	{
		name: "University of Missouri",
		shortName: "Missouri",
		mascot: "Tigers",
		conference: "SEC",
		city: "Columbia",
		state: "MO",
		lat: 38.2919,
		lon: -92.3388,
		colorPrimary: "#000000",
		colorSecondary: "#FFD700",
		hintRegion: "Midwest",
	},
	{
		name: "University of Oklahoma",
		shortName: "Oklahoma",
		mascot: "Sooners",
		conference: "SEC",
		city: "Norman",
		state: "OK",
		lat: 35.2087,
		lon: -97.4405,
		colorPrimary: "#CC0000",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southwest",
	},
	{
		name: "University of South Carolina",
		shortName: "South Carolina",
		mascot: "Gamecocks",
		conference: "SEC",
		city: "Columbia",
		state: "SC",
		lat: 34.1193,
		lon: -81.0263,
		colorPrimary: "#73000A",
		colorSecondary: "#000000",
		hintRegion: "Southeast",
	},
	{
		name: "University of Tennessee",
		shortName: "Tennessee",
		mascot: "Volunteers",
		conference: "SEC",
		city: "Knoxville",
		state: "TN",
		lat: 35.9558,
		lon: -83.9265,
		colorPrimary: "#FF8200",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southeast",
	},
	{
		name: "Texas A&M University",
		shortName: "Texas A&M",
		mascot: "Aggies",
		conference: "SEC",
		city: "College Station",
		state: "TX",
		lat: 30.6167,
		lon: -96.3422,
		colorPrimary: "#500000",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southwest",
	},
	{
		name: "University of Texas",
		shortName: "Texas",
		mascot: "Longhorns",
		conference: "SEC",
		city: "Austin",
		state: "TX",
		lat: 30.2833,
		lon: -97.7339,
		colorPrimary: "#CC5500",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southwest",
	},
	{
		name: "Vanderbilt University",
		shortName: "Vanderbilt",
		mascot: "Commodores",
		conference: "SEC",
		city: "Nashville",
		state: "TN",
		lat: 36.1446,
		lon: -86.8016,
		colorPrimary: "#000000",
		colorSecondary: "#FFD700",
		hintRegion: "Southeast",
	},

	// Big Ten (18 schools)
	{
		name: "University of Illinois",
		shortName: "Illinois",
		mascot: "Fighting Illini",
		conference: "Big Ten",
		city: "Urbana",
		state: "IL",
		lat: 40.1164,
		lon: -88.2434,
		colorPrimary: "#003D7A",
		colorSecondary: "#FF6600",
		hintRegion: "Midwest",
	},
	{
		name: "Indiana University",
		shortName: "Indiana",
		mascot: "Hoosiers",
		conference: "Big Ten",
		city: "Bloomington",
		state: "IN",
		lat: 39.1684,
		lon: -86.5244,
		colorPrimary: "#990000",
		colorSecondary: "#FFFFFF",
		hintRegion: "Midwest",
	},
	{
		name: "University of Iowa",
		shortName: "Iowa",
		mascot: "Hawkeyes",
		conference: "Big Ten",
		city: "Iowa City",
		state: "IA",
		lat: 41.9603,
		lon: -91.6350,
		colorPrimary: "#000000",
		colorSecondary: "#FFD700",
		hintRegion: "Midwest",
	},
	{
		name: "University of Maryland",
		shortName: "Maryland",
		mascot: "Terrapins",
		conference: "Big Ten",
		city: "College Park",
		state: "MD",
		lat: 38.9869,
		lon: -76.9426,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		hintRegion: "Northeast",
	},
	{
		name: "University of Michigan",
		shortName: "Michigan",
		mascot: "Wolverines",
		conference: "Big Ten",
		city: "Ann Arbor",
		state: "MI",
		lat: 42.2656,
		lon: -83.7430,
		colorPrimary: "#00274C",
		colorSecondary: "#FFCC00",
		hintRegion: "Midwest",
	},
	{
		name: "Michigan State University",
		shortName: "Michigan State",
		mascot: "Spartans",
		conference: "Big Ten",
		city: "East Lansing",
		state: "MI",
		lat: 42.7335,
		lon: -84.4867,
		colorPrimary: "#18453B",
		colorSecondary: "#FFFFFF",
		hintRegion: "Midwest",
	},
	{
		name: "University of Minnesota",
		shortName: "Minnesota",
		mascot: "Golden Gophers",
		conference: "Big Ten",
		city: "Minneapolis",
		state: "MN",
		lat: 44.9747,
		lon: -93.2277,
		colorPrimary: "#8B0000",
		colorSecondary: "#FFD700",
		hintRegion: "Midwest",
	},
	{
		name: "University of Nebraska",
		shortName: "Nebraska",
		mascot: "Cornhuskers",
		conference: "Big Ten",
		city: "Lincoln",
		state: "NE",
		lat: 40.8258,
		lon: -96.7017,
		colorPrimary: "#CC0000",
		colorSecondary: "#FFFFFF",
		hintRegion: "Midwest",
	},
	{
		name: "Northwestern University",
		shortName: "Northwestern",
		mascot: "Wildcats",
		conference: "Big Ten",
		city: "Evanston",
		state: "IL",
		lat: 42.0534,
		lon: -87.6738,
		colorPrimary: "#4D2DB7",
		colorSecondary: "#FFFFFF",
		hintRegion: "Midwest",
	},
	{
		name: "Ohio State University",
		shortName: "Ohio State",
		mascot: "Buckeyes",
		conference: "Big Ten",
		city: "Columbus",
		state: "OH",
		lat: 40.0084,
		lon: -83.1074,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		hintRegion: "Midwest",
	},
	{
		name: "University of Oregon",
		shortName: "Oregon",
		mascot: "Ducks",
		conference: "Big Ten",
		city: "Eugene",
		state: "OR",
		lat: 44.0521,
		lon: -123.0868,
		colorPrimary: "#003831",
		colorSecondary: "#FFC72C",
		hintRegion: "Pacific",
	},
	{
		name: "Pennsylvania State University",
		shortName: "Penn State",
		mascot: "Nittany Lions",
		conference: "Big Ten",
		city: "University Park",
		state: "PA",
		lat: 40.8135,
		lon: -77.8601,
		colorPrimary: "#001A66",
		colorSecondary: "#FFFFFF",
		hintRegion: "Northeast",
	},
	{
		name: "Purdue University",
		shortName: "Purdue",
		mascot: "Boilermakers",
		conference: "Big Ten",
		city: "West Lafayette",
		state: "IN",
		lat: 40.4258,
		lon: -87.0081,
		colorPrimary: "#000000",
		colorSecondary: "#FFD700",
		hintRegion: "Midwest",
	},
	{
		name: "Rutgers University",
		shortName: "Rutgers",
		mascot: "Scarlet Knights",
		conference: "Big Ten",
		city: "New Brunswick",
		state: "NJ",
		lat: 40.5243,
		lon: -74.4732,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		hintRegion: "Northeast",
	},
	{
		name: "University of Southern California",
		shortName: "USC",
		mascot: "Trojans",
		conference: "Big Ten",
		city: "Los Angeles",
		state: "CA",
		lat: 34.0195,
		lon: -118.2882,
		colorPrimary: "#990000",
		colorSecondary: "#FFD700",
		hintRegion: "Pacific",
	},
	{
		name: "University of California, Los Angeles",
		shortName: "UCLA",
		mascot: "Bruins",
		conference: "Big Ten",
		city: "Los Angeles",
		state: "CA",
		lat: 34.0709,
		lon: -118.4468,
		colorPrimary: "#003DA5",
		colorSecondary: "#FFD700",
		hintRegion: "Pacific",
	},
	{
		name: "University of Washington",
		shortName: "Washington",
		mascot: "Huskies",
		conference: "Big Ten",
		city: "Seattle",
		state: "WA",
		lat: 47.6550,
		lon: -122.3035,
		colorPrimary: "#4B2C6F",
		colorSecondary: "#FFD700",
		hintRegion: "Pacific",
	},
	{
		name: "University of Wisconsin",
		shortName: "Wisconsin",
		mascot: "Badgers",
		conference: "Big Ten",
		city: "Madison",
		state: "WI",
		lat: 43.0731,
		lon: -89.4012,
		colorPrimary: "#C60C30",
		colorSecondary: "#FFFFFF",
		hintRegion: "Midwest",
	},

	// Big 12 (16 schools)
	{
		name: "University of Arizona",
		shortName: "Arizona",
		mascot: "Wildcats",
		conference: "Big 12",
		city: "Tucson",
		state: "AZ",
		lat: 32.2319,
		lon: -110.9501,
		colorPrimary: "#0013A3",
		colorSecondary: "#CC0000",
		hintRegion: "Southwest",
	},
	{
		name: "Arizona State University",
		shortName: "Arizona State",
		mascot: "Sun Devils",
		conference: "Big 12",
		city: "Tempe",
		state: "AZ",
		lat: 33.4255,
		lon: -111.9286,
		colorPrimary: "#8B2252",
		colorSecondary: "#FFC52F",
		hintRegion: "Southwest",
	},
	{
		name: "Baylor University",
		shortName: "Baylor",
		mascot: "Bears",
		conference: "Big 12",
		city: "Waco",
		state: "TX",
		lat: 31.5486,
		lon: -97.1164,
		colorPrimary: "#003D7A",
		colorSecondary: "#FFD700",
		hintRegion: "Southwest",
	},
	{
		name: "Brigham Young University",
		shortName: "BYU",
		mascot: "Cougars",
		conference: "Big 12",
		city: "Provo",
		state: "UT",
		lat: 40.2338,
		lon: -111.6585,
		colorPrimary: "#003366",
		colorSecondary: "#FFFFFF",
		hintRegion: "Mountain",
	},
	{
		name: "University of Central Florida",
		shortName: "UCF",
		mascot: "Knights",
		conference: "Big 12",
		city: "Orlando",
		state: "FL",
		lat: 28.6024,
		lon: -81.2005,
		colorPrimary: "#000000",
		colorSecondary: "#FFD700",
		hintRegion: "Southeast",
	},
	{
		name: "University of Cincinnati",
		shortName: "Cincinnati",
		mascot: "Bearcats",
		conference: "Big 12",
		city: "Cincinnati",
		state: "OH",
		lat: 39.1331,
		lon: -84.5186,
		colorPrimary: "#000000",
		colorSecondary: "#EF3B39",
		hintRegion: "Midwest",
	},
	{
		name: "University of Colorado",
		shortName: "Colorado",
		mascot: "Buffaloes",
		conference: "Big 12",
		city: "Boulder",
		state: "CO",
		lat: 40.0064,
		lon: -105.2605,
		colorPrimary: "#000000",
		colorSecondary: "#FFCC00",
		hintRegion: "Mountain",
	},
	{
		name: "University of Houston",
		shortName: "Houston",
		mascot: "Cougars",
		conference: "Big 12",
		city: "Houston",
		state: "TX",
		lat: 29.7589,
		lon: -95.3677,
		colorPrimary: "#CC0000",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southwest",
	},
	{
		name: "Iowa State University",
		shortName: "Iowa State",
		mascot: "Cyclones",
		conference: "Big 12",
		city: "Ames",
		state: "IA",
		lat: 42.0115,
		lon: -93.6318,
		colorPrimary: "#990000",
		colorSecondary: "#FFD700",
		hintRegion: "Midwest",
	},
	{
		name: "University of Kansas",
		shortName: "Kansas",
		mascot: "Jayhawks",
		conference: "Big 12",
		city: "Lawrence",
		state: "KS",
		lat: 38.9596,
		lon: -95.2672,
		colorPrimary: "#0051BA",
		colorSecondary: "#EF4601",
		hintRegion: "Midwest",
	},
	{
		name: "Kansas State University",
		shortName: "Kansas State",
		mascot: "Wildcats",
		conference: "Big 12",
		city: "Manhattan",
		state: "KS",
		lat: 39.2184,
		lon: -97.5952,
		colorPrimary: "#512B82",
		colorSecondary: "#FFFFFF",
		hintRegion: "Midwest",
	},
	{
		name: "Oklahoma State University",
		shortName: "Oklahoma State",
		mascot: "Cowboys",
		conference: "Big 12",
		city: "Stillwater",
		state: "OK",
		lat: 36.1186,
		lon: -97.0734,
		colorPrimary: "#FF6A1D",
		colorSecondary: "#000000",
		hintRegion: "Southwest",
	},
	{
		name: "Texas Christian University",
		shortName: "TCU",
		mascot: "Horned Frogs",
		conference: "Big 12",
		city: "Fort Worth",
		state: "TX",
		lat: 32.7555,
		lon: -97.3308,
		colorPrimary: "#4D1979",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southwest",
	},
	{
		name: "Texas Tech University",
		shortName: "Texas Tech",
		mascot: "Red Raiders",
		conference: "Big 12",
		city: "Lubbock",
		state: "TX",
		lat: 33.5850,
		lon: -101.8746,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		hintRegion: "Southwest",
	},
	{
		name: "University of Utah",
		shortName: "Utah",
		mascot: "Utes",
		conference: "Big 12",
		city: "Salt Lake City",
		state: "UT",
		lat: 40.7629,
		lon: -111.8410,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		hintRegion: "Mountain",
	},
	{
		name: "West Virginia University",
		shortName: "West Virginia",
		mascot: "Mountaineers",
		conference: "Big 12",
		city: "Morgantown",
		state: "WV",
		lat: 39.6334,
		lon: -79.9559,
		colorPrimary: "#003366",
		colorSecondary: "#FFD700",
		hintRegion: "Southeast",
	},

	// ACC (18 schools)
	{
		name: "Boston College",
		shortName: "Boston College",
		mascot: "Eagles",
		conference: "ACC",
		city: "Chestnut Hill",
		state: "MA",
		lat: 42.3356,
		lon: -71.1677,
		colorPrimary: "#8B0000",
		colorSecondary: "#FFD700",
		hintRegion: "Northeast",
	},
	{
		name: "University of California, Berkeley",
		shortName: "Cal",
		mascot: "Golden Bears",
		conference: "ACC",
		city: "Berkeley",
		state: "CA",
		lat: 37.8722,
		lon: -122.2597,
		colorPrimary: "#003831",
		colorSecondary: "#FFD700",
		hintRegion: "Pacific",
	},
	{
		name: "Clemson University",
		shortName: "Clemson",
		mascot: "Tigers",
		conference: "ACC",
		city: "Clemson",
		state: "SC",
		lat: 34.6836,
		lon: -82.8374,
		colorPrimary: "#F66733",
		colorSecondary: "#522D80",
		hintRegion: "Southeast",
	},
	{
		name: "Duke University",
		shortName: "Duke",
		mascot: "Blue Devils",
		conference: "ACC",
		city: "Durham",
		state: "NC",
		lat: 36.0014,
		lon: -78.9382,
		colorPrimary: "#003366",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southeast",
	},
	{
		name: "Florida State University",
		shortName: "Florida State",
		mascot: "Seminoles",
		conference: "ACC",
		city: "Tallahassee",
		state: "FL",
		lat: 30.4383,
		lon: -84.2807,
		colorPrimary: "#8B0000",
		colorSecondary: "#FFD700",
		hintRegion: "Southeast",
	},
	{
		name: "Georgia Institute of Technology",
		shortName: "Georgia Tech",
		mascot: "Yellow Jackets",
		conference: "ACC",
		city: "Atlanta",
		state: "GA",
		lat: 33.7756,
		lon: -84.3963,
		colorPrimary: "#FFD700",
		colorSecondary: "#000000",
		hintRegion: "Southeast",
	},
	{
		name: "University of Louisville",
		shortName: "Louisville",
		mascot: "Cardinals",
		conference: "ACC",
		city: "Louisville",
		state: "KY",
		lat: 38.2009,
		lon: -85.7585,
		colorPrimary: "#CC0000",
		colorSecondary: "#000000",
		hintRegion: "Southeast",
	},
	{
		name: "University of Miami",
		shortName: "Miami",
		mascot: "Hurricanes",
		conference: "ACC",
		city: "Coral Gables",
		state: "FL",
		lat: 25.7247,
		lon: -80.2798,
		colorPrimary: "#00843D",
		colorSecondary: "#F47D31",
		hintRegion: "Southeast",
	},
	{
		name: "University of North Carolina",
		shortName: "North Carolina",
		mascot: "Tar Heels",
		conference: "ACC",
		city: "Chapel Hill",
		state: "NC",
		lat: 35.9064,
		lon: -79.0469,
		colorPrimary: "#4B9CD3",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southeast",
	},
	{
		name: "North Carolina State University",
		shortName: "NC State",
		mascot: "Wolfpack",
		conference: "ACC",
		city: "Raleigh",
		state: "NC",
		lat: 35.7796,
		lon: -78.6382,
		colorPrimary: "#CC0000",
		colorSecondary: "#FFFFFF",
		hintRegion: "Southeast",
	},
	{
		name: "University of Notre Dame",
		shortName: "Notre Dame",
		mascot: "Fighting Irish",
		conference: "ACC",
		city: "Notre Dame",
		state: "IN",
		lat: 41.7029,
		lon: -86.2394,
		colorPrimary: "#003366",
		colorSecondary: "#FFD700",
		hintRegion: "Midwest",
	},
	{
		name: "University of Pittsburgh",
		shortName: "Pittsburgh",
		mascot: "Panthers",
		conference: "ACC",
		city: "Pittsburgh",
		state: "PA",
		lat: 40.4426,
		lon: -79.9626,
		colorPrimary: "#003366",
		colorSecondary: "#FFD700",
		hintRegion: "Northeast",
	},
	{
		name: "Southern Methodist University",
		shortName: "SMU",
		mascot: "Mustangs",
		conference: "ACC",
		city: "Dallas",
		state: "TX",
		lat: 32.8431,
		lon: -96.7816,
		colorPrimary: "#CC0000",
		colorSecondary: "#003366",
		hintRegion: "Southwest",
	},
	{
		name: "Stanford University",
		shortName: "Stanford",
		mascot: "Cardinal",
		conference: "ACC",
		city: "Stanford",
		state: "CA",
		lat: 37.4275,
		lon: -122.1697,
		colorPrimary: "#8B0000",
		colorSecondary: "#FFFFFF",
		hintRegion: "Pacific",
	},
	{
		name: "Syracuse University",
		shortName: "Syracuse",
		mascot: "Orange",
		conference: "ACC",
		city: "Syracuse",
		state: "NY",
		lat: 43.0514,
		lon: -76.1474,
		colorPrimary: "#FF6600",
		colorSecondary: "#003366",
		hintRegion: "Northeast",
	},
	{
		name: "University of Virginia",
		shortName: "Virginia",
		mascot: "Cavaliers",
		conference: "ACC",
		city: "Charlottesville",
		state: "VA",
		lat: 38.0336,
		lon: -78.5080,
		colorPrimary: "#003366",
		colorSecondary: "#FF6600",
		hintRegion: "Southeast",
	},
	{
		name: "Virginia Polytechnic Institute and State University",
		shortName: "Virginia Tech",
		mascot: "Hokies",
		conference: "ACC",
		city: "Blacksburg",
		state: "VA",
		lat: 37.2296,
		lon: -80.4139,
		colorPrimary: "#8B0000",
		colorSecondary: "#FF8200",
		hintRegion: "Southeast",
	},
	{
		name: "Wake Forest University",
		shortName: "Wake Forest",
		mascot: "Demon Deacons",
		conference: "ACC",
		city: "Winston-Salem",
		state: "NC",
		lat: 36.1326,
		lon: -80.2845,
		colorPrimary: "#000000",
		colorSecondary: "#FFD700",
		hintRegion: "Southeast",
	},
];

var CONFERENCES = ["SEC", "Big Ten", "Big 12", "ACC"];

var SUBREGIONS = {
	"Northeast": ["ME","NH","VT","MA","RI","CT","NY","NJ","PA","MD","DE","DC"],
	"Southeast": ["VA","WV","NC","SC","GA","FL","AL","MS","TN","KY","LA","AR"],
	"Midwest": ["OH","IN","IL","MI","WI","MN","IA","MO","ND","SD","NE","KS"],
	"Southwest": ["TX","OK","NM","AZ"],
	"Mountain": ["CO","UT","WY","MT","ID","NV"],
	"Pacific": ["WA","OR","CA"],
};
